remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Qirui Zheng
description: UCSD Undergraduate Student majoring in Data Science and Cognitive Science
logo: assets/qz-img.jpeg